<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NewDoor.PlatformShared\NewDoor.Platform.DTO\NewDoor.Platform.DTO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DoWhatta.Platform">
      <HintPath>..\..\Resource\dowhatta\DoWhatta.Platform.dll</HintPath>
    </Reference>
    <Reference Include="DoWhatta.Platform.DTO">
      <HintPath>..\..\Resource\dowhatta\DoWhatta.Platform.DTO.dll</HintPath>
    </Reference>
    <Reference Include="Higgs.Blazor">
      <HintPath>..\..\Resource\HiggsBlazor\Higgs.Blazor.dll</HintPath>
    </Reference>
    <Reference Include="Higgs.Blazor.Foundation">
      <HintPath>..\..\Resource\HiggsBlazor\Higgs.Blazor.Foundation.dll</HintPath>
    </Reference>
    <Reference Include="Higgs.Blazor.Theme">
      <HintPath>..\..\Resource\HiggsBlazor\Higgs.Blazor.Theme.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
