<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DoWhatta.Platform.Entities">
      <HintPath>..\..\Resource\dowhatta\DoWhatta.Platform.Entities.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
